version: 0.2
phases:
  pre_build:
    commands:
      - echo 'prebuild'
      - printenv
  build:
    commands:
      - echo 'Compiling the Go Code HEllo'
      - sleep 10
  post_build:
    commands:
      - echo "Would deploy here"
